os: linux
language: node_js

node_js:
  - 10
  - stable

git:
  depth: 5

install:
  - yarn
  - npx lerna bootstrap

cache:
  - npm
  - yarn

script:
  - yarn test

after_success:
  - bash <(curl -s https://codecov.io/bash)
