language: node_js
node_js:
  - 9
  - 10
  - 11
  - 12
  - stable
cache: yarn

script:
  - cd packages/engine
  - yarn
  - yarn test --coverage
  - bash <(curl -s https://codecov.io/bash)
  - cd ../..
  - cd packages/provider-sendgrid
  - yarn
  - yarn test --coverage
  - bash <(curl -s https://codecov.io/bash)
  - cd ../..
