language: node_js

node_js:
  - 10
  - stable

cache:
  - npm
  - yarn

git:
  depth: 5

install:
  - npx lerna bootstrap

script:
  - cd packages/macaw && yarn test --coverage && cd ../..
  - cd packages/provider-sendgrid && yarn test --coverage && cd ../..

after_success:
  - bash <(curl -s https://codecov.io/bash)

before_deploy:
  - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
  - git remote set-url origin https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
  - git checkout master
  - git pull origin master

deploy:
  provider: script
  cleanup: false
  script: npx lerna publish --yes
  on:
    branch: master
